
import Footer from "@/components/Footer";
import "./globals.css";
import Header from "@/components/Header";

import { Inter, Roboto , Roboto_Serif   } from "next/font/google";

const roboto= Roboto({
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter ({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

const robo_serif = Roboto_Serif ({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "TechDev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"
    style={{
      "--ff-roboto": roboto.style.fontFamily,
      "--ff-inter": inter.style.fontFamily,
      "--ff-robo_serif": robo_serif.style.fontFamily,
    }}>
      
      <link rel="icon" href="./favicon.ico" sizes="any" />
      
      <body className= {`${roboto.className} bg-blue-bg ` }  >
        <Header/>
        {children}
      <Footer/>
        </body>
    </html>
  );
}
